version: "3"

services:
  server:
    build: .
    restart: always
    environment:
      DATABASE_DSN: postgres://admin:password@database:5432/postgres?sslmode=disable
    networks:
      - bigpay
    ports:
      - 8080:1323
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - .:/srv
    networks:
      - bigpay
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  dbconsole:
    image: dpage/pgadmin4
    networks:
      - bigpay
    ports:
      - 54321:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database

networks:
  bigpay:

